name: my_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_secure_storage: ^9.2.2
  file_picker: ^8.1.4
  flutter_excel: ^1.0.1
  flutter_highlight: ^0.7.0
  url_launcher: ^6.3.1
  drift: ^2.21.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.0
  intl: ^0.19.0
  flutter_colorpicker: ^1.1.0
  drift_flutter: ^0.2.1
  sqlite3: ^2.4.7
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  desktop_window: ^0.4.2

dev_dependencies:

  flutter_test:
    sdk: flutter
  build_web_compilers: ^4.0.0
  flutter_lints: ^2.0.0
  drift_dev: ^2.8.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
